version: '3'
services:
  app:
    container_name: node-app
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules